name: Build Site

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Pandoc
      uses: pandoc/actions/setup@v1
      with:
        version: 3.8

    - name: Install Task
      uses: go-task/setup-task@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt 

    - name: Build Site
      run: |
        mkdir html
        task build

    - name: Upload Artifacts
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: html/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

